import java_cup.runtime;

terminal PTVIRG,MAIS,MENOS;

terminal Integer INTEIRO;

non terminal Object expr_list,expr_ptv;

non terminal Integer expr;

expr_list ::= expr_list expr_ptv
	| expr_ptv;


expr_ptv ::= expr:e {: System.out.println("="+e.intValue()); :}PTVIRG;

expr ::= INTEIRO:n MAIS expr:e
	{: RESULT = new Integer(n.intValue() + e.intValue()); :}
	|	INTEIRO:n MENOS expr:e
	{: RESULT = new Integer(n.intValue() - e.intValue()); :}
	|	INTEIRO:n
	{: RESULT = n; :};
