
//----------------------------------------------------
// The following code was generated by jh-javacup-1.2 20210807
// Thu Oct 19 13:29:55 BRT 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int PTVIRG = 2;
  public static final int MAIS = 3;
  public static final int MENOS = 4;
  public static final int INTEIRO = 5;
}

